import React from 'react';
import { 
  Home, Search, MessageCircle, User, Calendar, BookOpen, Bell, Award, Users
} from 'lucide-react';
import { Post, AnalyticsData, ChatConversation, College, AuthorityRole } from './types';

export const NAV_ITEMS = [
  { id: 'home', label: 'Pulse Feed', icon: <Home size={22} /> },
  { id: 'groups', label: 'Groups Hub', icon: <Users size={22} /> },
  { id: 'search', label: 'Registry', icon: <Search size={22} /> },
  { id: 'calendar', label: 'Schedule', icon: <Calendar size={22} /> },
  { id: 'resources', label: 'The Vault', icon: <BookOpen size={22} /> },
  { id: 'notifications', label: 'Signals', icon: <Bell size={22} /> },
  { id: 'messages', label: 'Uplink', icon: <MessageCircle size={22} /> },
  { id: 'profile', label: 'Terminal', icon: <User size={22} /> },
];

export const COLLEGE_BANNERS: Record<College, string> = {
  COCIS: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200',
  CEDAT: 'https://images.unsplash.com/photo-1503387762-592dea58ef23?auto=format&fit=crop&w=1200',
  CHUSS: 'https://images.unsplash.com/photo-1491843384429-181717b8e24f?auto=format&fit=crop&w=1200',
  CHS: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=1200',
  CONAS: 'https://images.unsplash.com/photo-1532187875605-183881249611?auto=format&fit=crop&w=1200',
  CAES: 'https://images.unsplash.com/photo-1495107336214-bca9f1d95c18?auto=format&fit=crop&w=1200',
  COBAMS: 'https://images.unsplash.com/photo-1454165833767-02a6e30996d4?auto=format&fit=crop&w=1200',
  CEES: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=1200',
  LAW: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200'
};

export const MOCK_POSTS: Post[] = [
  {
    id: 'p-vc-1',
    author: 'Prof. Barnabas Nawangwe',
    authorId: 'vc_office',
    authorRole: 'Vice Chancellor',
    authorAvatar: 'https://marcopolis.net/wp-content/uploads/uganda_report/2020/interviews/makerere_university/Professor_Barnabas_Nawangwe_Vice_Chancellor_of_Makerere_University.jpg',
    authorAuthority: 'Administrator',
    timestamp: '15m ago',
    content: `<h1>Central Administration Directive</h1><p>The University Council has officially synchronized the new research innovation strata. We are prioritizing the development of local logic hubs in all colleges.</p>`,
    hashtags: ['#RegistrySync', '#MakerereResearch'],
    likes: 1240,
    commentsCount: 45,
    comments: [],
    views: 12000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-ad-mtn',
    author: 'MTN Uganda',
    authorId: 'mtn_partner',
    authorRole: 'Pulse Partner',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=MTN',
    authorAuthority: 'Corporate',
    isAd: true,
    timestamp: 'Just now',
    content: `<h1>MTN Pulse: Data Synchronization</h1><p>Fuel your research node with the most aggressive data bundles on the Hill. Dial *157# to sync your device with the Pulse strata.</p>`,
    hashtags: ['#MTNPulse', '#UnlimitedSync'],
    likes: 840,
    commentsCount: 12,
    comments: [],
    views: 45000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1556742044-3c52d6e88c62?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-lib-1',
    author: 'Main Library Node',
    authorId: 'mak_library',
    authorRole: 'Official Hub',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=Library',
    authorAuthority: 'Official',
    timestamp: '1h ago',
    content: `<h1>Vault Maintenance Advisory</h1><p>The electronic journal strata will undergo a logic synchronization tonight at 2300hrs. Access to JSTOR and IEEE nodes may experience latency.</p>`,
    hashtags: ['#TheVault', '#ResearchIntegrity'],
    likes: 312,
    commentsCount: 8,
    comments: [],
    views: 5600,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-unipod-1',
    author: 'Mak UniPod',
    authorId: 'mak_unipod',
    authorRole: 'Innovation Forge',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=UniPod',
    authorAuthority: 'Official',
    timestamp: '2h ago',
    content: `<h1>Prototyping Cycle: Alpha Node</h1><p>New 3D printing protocols are now active for all engineering and computing finalists. Visit the Forge to synchronize your blueprints.</p>`,
    hashtags: ['#UniPod', '#Fabrication'],
    likes: 560,
    commentsCount: 14,
    comments: [],
    views: 8900,
    flags: [],
    isOpportunity: false,
    college: 'CEDAT',
    images: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-guild-1',
    author: 'Guild Presidential Office',
    authorId: 'guild_office',
    authorRole: 'Student Leadership',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Guild',
    authorAuthority: 'Student Leader',
    timestamp: '3h ago',
    content: `<h1>Leadership Signal</h1><p>The 89th Guild has successfully negotiated the restoration of student allowance nodes for the upcoming semester. Distribution sync starts Monday.</p>`,
    hashtags: ['#Guild89', '#StudentWelfare'],
    likes: 2100,
    commentsCount: 156,
    comments: [],
    views: 32000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1540575861501-7cf05a4b125a?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-lec-1',
    author: 'Dr. Julianne O.',
    authorId: 'u-julianne',
    authorRole: 'Senior Lecturer',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Julianne',
    authorAuthority: 'Lecturer',
    timestamp: '4h ago',
    content: `<h1>Course Update: CS3102</h1><p>I have committed the final prep notes for Advanced Computer Architecture to the COCIS Vault. Finalists should sync their local nodes immediately.</p>`,
    hashtags: ['#Architecture', '#FinalsPrep'],
    likes: 156,
    commentsCount: 8,
    comments: [],
    views: 1200,
    flags: [],
    isOpportunity: false,
    college: 'COCIS',
    images: ['https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-ad-airtel',
    author: 'Airtel Uganda',
    authorId: 'airtel_partner',
    authorRole: 'Network Partner',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=Airtel',
    authorAuthority: 'Corporate',
    isAd: true,
    timestamp: '5h ago',
    content: `<h1>A Reason to Imagine: University Bundles</h1><p>Switch to the smartphone network. Get un-throttled access to Microsoft Teams and Zoom for your online research modules. Dial *175*3#.</p>`,
    hashtags: ['#AirtelUniv', '#Imagination'],
    likes: 3100,
    commentsCount: 45,
    comments: [],
    views: 65000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-sec-1',
    author: 'Security Registry',
    authorId: 'mak_security',
    authorRole: 'Official Channel',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=Security',
    authorAuthority: 'Official',
    timestamp: '6h ago',
    content: `<p>Registry Advisory: All students must update their digital identity IDs before the physical blackout at 2200hrs. Patrol nodes are active.</p>`,
    hashtags: ['#CampusSafety', '#Notice'],
    likes: 890,
    commentsCount: 32,
    comments: [],
    views: 22000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1557597774-9d2739f85a76?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-law-1',
    author: 'Counsel Peter',
    authorId: 'u-peter',
    authorRole: 'Legal Advisor',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Peter',
    authorAuthority: 'Official',
    timestamp: '7h ago',
    content: `<h1>Legal Clinic Strata</h1><p>Providing free legal advice nodes to all first-year students regarding guild constitution violations. Visit the LAW wing room 4B.</p>`,
    hashtags: ['#LegalTech', '#Justice'],
    likes: 412,
    commentsCount: 25,
    comments: [],
    views: 3400,
    flags: [],
    isOpportunity: false,
    college: 'LAW',
    images: ['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-ad-stanbic',
    author: 'Stanbic Bank',
    authorId: 'stanbic_partner',
    authorRole: 'Finance Node',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=Stanbic',
    authorAuthority: 'Corporate',
    isAd: true,
    timestamp: '8h ago',
    content: `<h1>Flexi-Pay: Seamless Tuition</h1><p>Settle your university dues without leaving your wing. Flexi-Pay is now synchronized with the Makerere Central Finance Hub.</p>`,
    hashtags: ['#EasyBanking', '#MakerereFlex'],
    likes: 1500,
    commentsCount: 12,
    comments: [],
    views: 42000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1556742044-3c52d6e88c62?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-chs-1',
    author: 'Dr. Nalule',
    authorId: 'u-nalule',
    authorRole: 'Medical Lead',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nalule',
    authorAuthority: 'Official',
    timestamp: '9h ago',
    content: `<h1>Health Alert: Resilience Sync</h1><p>Flu nodes detected in the CHS wing. Ensure your wellness telemetry is updated. Free medical checks at the university clinic.</p>`,
    hashtags: ['#HealthFirst', '#MakerereWellness'],
    likes: 560,
    commentsCount: 14,
    comments: [],
    views: 8900,
    flags: [],
    isOpportunity: false,
    college: 'CHS',
    images: ['https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-opp-2',
    author: 'World Bank Node',
    authorId: 'wb_node',
    authorRole: 'Grant Provider',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=WorldBank',
    authorAuthority: 'Official',
    timestamp: '10h ago',
    isOpportunity: true,
    opportunityData: {
      type: 'Grant',
      isAIVerified: true,
      detectedBenefit: 'UGX 15M Fund'
    },
    content: `<h1>Research Grant: Sustainable Hill Architecture</h1><p>We are seeking innovative logic proposals for solar-powered student labs. Open to CEDAT and COCIS finalists.</p>`,
    hashtags: ['#Sustainability', '#GrantAccess'],
    likes: 950,
    commentsCount: 42,
    comments: [],
    views: 18000,
    flags: [],
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1503387762-592dea58ef23?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-news-1',
    author: 'Mak Pulse News',
    authorId: 'pulse_news',
    authorRole: 'Media Wing',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=Pulse',
    authorAuthority: 'Official',
    timestamp: '11h ago',
    content: `<h1>Breaking: Examination Blockout</h1><p>The University Council has officially authorized the examination dates. Logic testing begins on 12th December for all colleges.</p>`,
    hashtags: ['#ExamSeason', '#MakerereNews'],
    likes: 2100,
    commentsCount: 450,
    comments: [],
    views: 48000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-stud-1',
    author: 'Ninfa Monaldo',
    authorId: 'u-ninfa',
    authorRole: 'Web Architect',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ninfa',
    timestamp: '12h ago',
    content: `<p>Just finished optimizing the logic strata for my final project. React + Tailwind on the Hill is the ultimate stack. 🚀</p>`,
    hashtags: ['#WebDev', '#SoftwareProject'],
    likes: 89,
    commentsCount: 4,
    comments: [],
    views: 800,
    flags: [],
    isOpportunity: false,
    college: 'COCIS',
    images: ['https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-opio-1',
    author: 'Opio Derrick',
    authorId: 'u-opio',
    authorRole: 'Agri Researcher',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Opio',
    timestamp: '13h ago',
    content: `<p>Field report from the CAES farm wing: The new irrigation sensors are transmitting perfect telemetry. Precision farming is the future of the Pearl.</p>`,
    hashtags: ['#AgriTech', '#CAES'],
    likes: 112,
    commentsCount: 3,
    comments: [],
    views: 1100,
    flags: [],
    isOpportunity: false,
    college: 'CAES',
    images: ['https://images.unsplash.com/photo-1495107336214-bca9f1d95c18?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-grc-cedat',
    author: 'Mugisha P.',
    authorId: 'u-mugisha',
    authorRole: 'GRC CEDAT',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mugisha',
    authorAuthority: 'GRC',
    timestamp: '14h ago',
    content: `<p>Resolved: The CEDAT common room will now have a permanent Wi-Fi node powered by the Guild Research budget. Stable uplink for all engineers.</p>`,
    hashtags: ['#TechAccess', '#CEDATLife'],
    likes: 620,
    commentsCount: 15,
    comments: [],
    views: 3200,
    flags: [],
    isOpportunity: false,
    college: 'CEDAT',
    images: ['https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-ad-vivo',
    author: 'Vivo Energy',
    authorId: 'vivo_partner',
    authorRole: 'Energy Node',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=Vivo',
    authorAuthority: 'Corporate',
    isAd: true,
    timestamp: '15h ago',
    content: `<h1>Shell FuelSave: The Hill Mobility</h1><p>Keeping the university transport nodes synchronized. Get your Shell Card today for subsidized fuel strata.</p>`,
    hashtags: ['#ShellFuelSave', '#LogisticsSync'],
    likes: 450,
    commentsCount: 5,
    comments: [],
    views: 12000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1620288627223-53302f4e8c74?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-cees-1',
    author: 'Dr. Mukasa',
    authorId: 'u-mukasa',
    authorRole: 'Education Dean',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mukasa',
    authorAuthority: 'Administrator',
    timestamp: '16h ago',
    content: `<h1>Education Strata Expansion</h1><p>We are opening new pedagogical labs for Year 2 nodes. Experience the future of teaching logic in the CEES wing.</p>`,
    hashtags: ['#CEES', '#TeacherSync'],
    likes: 245,
    commentsCount: 18,
    comments: [],
    views: 4500,
    flags: [],
    isOpportunity: false,
    college: 'CEES',
    images: ['https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-hospital-1',
    author: 'Mak Hospital Node',
    authorId: 'mak_hospital',
    authorRole: 'Health Hub',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=Hospital',
    authorAuthority: 'Official',
    timestamp: '17h ago',
    content: `<p>Identity Registry: Free vaccinations nodes for all verified students available in the CHS Medical Wing. Synchronize your health status today.</p>`,
    hashtags: ['#CampusHealth', '#ShieldUp'],
    likes: 1300,
    commentsCount: 88,
    comments: [],
    views: 18000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200']
  },
  {
    id: 'p-ad-michelin',
    author: 'Michelin Tires',
    authorId: 'michelin_partner',
    authorRole: 'Safety Node',
    authorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=Michelin',
    authorAuthority: 'Corporate',
    isAd: true,
    timestamp: '18h ago',
    content: `<h1>Grip The Hill</h1><p>Engineered for the tough Makerere terrains. Ensure your logistics node is fitted with Michelin logic for 100% safety synchronization.</p>`,
    hashtags: ['#SafetyRegistry', '#HillGrip'],
    likes: 670,
    commentsCount: 9,
    comments: [],
    views: 15000,
    flags: [],
    isOpportunity: false,
    college: 'Global',
    images: ['https://images.unsplash.com/photo-1544531585-9847b68c8c86?auto=format&fit=crop&w=1200']
  }
];

export const MOCK_CHATS: ChatConversation[] = [
  {
    id: 'chat-1',
    user: { name: 'Dr. Julianne O.', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Julianne', status: 'online', role: 'Faculty Node' },
    unreadCount: 2,
    lastMessage: 'Handshake successful. Ready for uplink.',
    lastTimestamp: '10:01 AM',
    isGroup: false,
    messages: [
      { id: 'm1', text: 'Initializing protocol...', timestamp: '10:00 AM', isMe: false },
      { id: 'm2', text: 'Handshake successful. Ready for uplink.', timestamp: '10:01 AM', isMe: false }
    ]
  }
];

export const ANALYTICS: AnalyticsData[] = [
  { day: 'Mon', posts: 120, activeUsers: 450, messages: 1200, revenue: 400, engagement: 1275 },
  { day: 'Tue', posts: 145, activeUsers: 480, messages: 1350, revenue: 420, engagement: 1350 },
  { day: 'Wed', posts: 180, activeUsers: 520, messages: 1600, revenue: 500, engagement: 1550 },
  { day: 'Thu', posts: 210, activeUsers: 600, messages: 1900, revenue: 620, engagement: 1800 },
  { day: 'Fri', posts: 240, activeUsers: 710, messages: 2400, revenue: 780, engagement: 2100 },
  { day: 'Sat', posts: 110, activeUsers: 320, messages: 900, revenue: 350, engagement: 950 },
  { day: 'Sun', posts: 90, activeUsers: 280, messages: 750, revenue: 280, engagement: 820 }
];
