
import React from 'react';
import { 
  Home, Search, Compass, MessageCircle, LayoutGrid, User, Calendar
} from 'lucide-react';
import { Post, AnalyticsData, ChatConversation } from './types';

export const NAV_ITEMS = [
  { id: 'home', label: 'Home', icon: <Home size={22} /> },
  { id: 'search', label: 'Search', icon: <Search size={22} /> },
  { id: 'calendar', label: 'Calendar', icon: <Calendar size={22} /> },
  { id: 'explore', label: 'Explore', icon: <Compass size={22} /> },
  { id: 'messages', label: 'Messages', icon: <MessageCircle size={22} /> },
  { id: 'groups', label: 'Colleges', icon: <LayoutGrid size={22} /> },
  { id: 'profile', label: 'Profile', icon: <User size={22} /> },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'maktv-1',
    author: 'MakTV Media',
    authorId: 'admin',
    authorRole: 'Official Media',
    authorAvatar: 'https://raw.githubusercontent.com/AshrafGit256/MakSocialImages/main/Public/MakSocial10.png',
    timestamp: '10 mins ago',
    content: 'MAK NEWS HOUR: Journalism students review the new campus security measures and the upcoming guild elections.',
    hashtags: ['#MakNews', '#Journalism', '#Makerere'],
    video: 'https://raw.githubusercontent.com/AshrafGit256/MakSocialImages/main/Public/journalism2.mp4',
    likes: 850,
    comments: [],
    commentsCount: 45,
    views: 5200,
    flags: [],
    isOpportunity: false,
    college: 'Global' as any,
    isMakTV: true,
    makTVType: 'News'
  },
  {
    id: 'u3-post-1',
    author: 'Sarah Nakato',
    authorId: 'u3',
    authorRole: 'Law Student',
    authorAvatar: 'https://i.pravatar.cc/150?u=sarah',
    timestamp: '30 mins ago',
    content: 'The Law Society is hosting a mock trial session in the Main Building this Friday. All law students are encouraged to attend!',
    hashtags: ['#MakLaw', '#MockTrial'],
    likes: 124,
    comments: [],
    commentsCount: 15,
    views: 450,
    flags: [],
    isOpportunity: false,
    college: 'LAW',
    aiMetadata: { sentiment: 'Positive', category: 'Social' }
  },
  {
    id: 'u5-post-1',
    author: 'Maria Kyazze',
    authorId: 'u5',
    authorRole: 'Med Student',
    authorAvatar: 'https://i.pravatar.cc/150?u=maria',
    timestamp: '1 hour ago',
    content: 'Research shows that consistent sleep schedules drastically improve memory retention for medical students. Don’t burn the midnight oil too often!',
    hashtags: ['#HealthTips', '#MakMedicine'],
    likes: 312,
    comments: [],
    commentsCount: 42,
    views: 1200,
    flags: [],
    isOpportunity: false,
    college: 'CHS',
    aiMetadata: { sentiment: 'Positive', category: 'Academic' }
  },
  {
    id: 'maktv-2',
    author: 'MakTV Spotlight',
    authorId: 'admin',
    authorRole: 'Official Media',
    authorAvatar: 'https://raw.githubusercontent.com/AshrafGit256/MakSocialImages/main/Public/MakSocial10.png',
    timestamp: '2 hours ago',
    content: 'ALUMNI INTERVIEW: Hon. Gerald Karuhanga shares his journey from Makerere Law School to National Leadership.',
    hashtags: ['#AlumniSpotlight', '#MakLaw', '#Inspiration'],
    video: 'https://raw.githubusercontent.com/AshrafGit256/MakSocialImages/main/Public/interview1.mp4',
    likes: 1200,
    comments: [],
    commentsCount: 130,
    views: 8900,
    flags: [],
    isOpportunity: false,
    college: 'LAW',
    isMakTV: true,
    makTVType: 'Interview',
    makTVGuest: 'Hon. Gerald Karuhanga'
  },
  {
    id: 'u4-post-1',
    author: 'Brian Okello',
    authorId: 'u4',
    authorRole: 'Eng Student',
    authorAvatar: 'https://i.pravatar.cc/150?u=brian',
    timestamp: '4 hours ago',
    content: 'Just finished assembling my first robotics kit in the CEDAT lab! If anyone wants to collaborate on an automated campus guide, DM me.',
    hashtags: ['#CEDAT', '#Robotics', '#Innovation'],
    images: ['https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800'],
    likes: 98,
    comments: [],
    commentsCount: 22,
    views: 340,
    flags: [],
    isOpportunity: true,
    college: 'CEDAT',
    aiMetadata: { sentiment: 'Positive', category: 'Career' }
  },
  {
    id: '1',
    author: 'Guru A.',
    authorId: 'u1',
    authorRole: 'CS Student',
    authorAvatar: 'https://raw.githubusercontent.com/AshrafGit256/MakSocialImages/main/Public/Ashraf.jpeg',
    timestamp: '5 hours ago',
    content: 'Excited about the new AI lab in COCIS block B!',
    hashtags: ['#COCIS', '#AI', '#Makerere'],
    images: ['https://cocis.mak.ac.ug/wp-content/uploads/2023/12/IMG_8833.jpg'],
    likes: 42,
    comments: [],
    commentsCount: 12,
    views: 120,
    flags: [],
    isOpportunity: false,
    college: 'COCIS',
    aiMetadata: { sentiment: 'Positive', category: 'Academic' }
  },
  {
    id: 'u7-post-1',
    author: 'Ivan Tumwine',
    authorId: 'u7',
    authorRole: 'Science Student',
    authorAvatar: 'https://i.pravatar.cc/150?u=ivan',
    timestamp: '6 hours ago',
    content: 'Looking for a study group for Advanced Biochemistry. We meet at CONAS room 102 every Tuesday.',
    hashtags: ['#CONAS', '#Biochemistry', '#StudyGroup'],
    likes: 56,
    comments: [],
    commentsCount: 9,
    views: 210,
    flags: [],
    isOpportunity: false,
    college: 'CONAS',
    aiMetadata: { sentiment: 'Neutral', category: 'Academic' }
  },
  {
    id: 'ad-img-1',
    author: 'MTN Uganda',
    authorId: 'ad1',
    authorRole: 'Brand Partner',
    authorAvatar: 'https://logo.clearbit.com/mtn.co.ug',
    timestamp: 'Sponsored',
    content: 'Upgrade your campus experience with Unbeatable Student Data Bundles. Dial *150*6# to join Pulse today!',
    hashtags: ['#MTNPulse', '#MakerereData'],
    video: 'https://raw.githubusercontent.com/AshrafGit256/MakSocialImages/main/Public/MTN.mp4',
    likes: 1205,
    comments: [],
    commentsCount: 88,
    views: 12400,
    flags: [],
    isOpportunity: false,
    college: 'Global' as any,
    isAd: true,
    adPartnerName: 'MTN Pulse',
    adCtaText: 'Get Bundles',
    adLink: 'https://www.mtn.co.ug/pulse/'
  },
  {
    id: 'u6-post-1',
    author: 'David Lule',
    authorId: 'u6',
    authorRole: 'Econ Student',
    authorAvatar: 'https://i.pravatar.cc/150?u=david',
    timestamp: '1 day ago',
    content: 'Has anyone seen the recent inflation data for East Africa? Might be a good topic for our next economics debate.',
    hashtags: ['#COBAMS', '#Economics', '#EAFinance'],
    likes: 24,
    comments: [],
    commentsCount: 4,
    views: 110,
    flags: [],
    isOpportunity: false,
    college: 'COBAMS',
    aiMetadata: { sentiment: 'Neutral', category: 'Academic' }
  }
];

export const ANALYTICS: AnalyticsData[] = [
  { day: 'Mon', posts: 120, activeUsers: 450, messages: 1200, revenue: 400, engagement: 1275 },
  { day: 'Tue', posts: 150, activeUsers: 520, messages: 1400, revenue: 600, engagement: 1530 },
  { day: 'Wed', posts: 200, activeUsers: 600, messages: 1800, revenue: 550, engagement: 1900 },
  { day: 'Thu', posts: 180, activeUsers: 580, messages: 1600, revenue: 800, engagement: 1770 },
  { day: 'Fri', posts: 250, activeUsers: 720, messages: 2100, revenue: 1200, engagement: 2330 },
  { day: 'Sat', posts: 100, activeUsers: 300, messages: 800, revenue: 400, engagement: 950 },
  { day: 'Sun', posts: 80, activeUsers: 250, messages: 600, revenue: 300, engagement: 775 },
];

export const MOCK_CHATS: ChatConversation[] = [
  {
    id: 'c1',
    user: { name: 'Guru A.', avatar: 'https://raw.githubusercontent.com/AshrafGit256/MakSocialImages/main/Public/Ashraf.jpeg'},
    lastMessage: 'The notes are on the portal.',
    unreadCount: 2,
    messages: [
      { id: 'm1', text: 'Hey, did you see the new assignment?', timestamp: '10:00 AM', isMe: false },
      { id: 'm2', text: 'Yes, just started working on it.', timestamp: '10:05 AM', isMe: true },
      { id: 'm3', text: 'The notes are on the portal.', timestamp: '10:10 AM', isMe: false },
    ]
  }
];
